# Perfil localstack — activar con SPRING_PROFILES_ACTIVE=localstack (docker compose local)
spring.cloud.aws.endpoint=http://localstack:4566
spring.cloud.aws.sqs.endpoint=http://localstack:4566
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
